# Gitlab CI configuration file

# Reference: https://hub.docker.com/_/node/
image: node:12.13.0

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service
services:
  # No services are currently declared

# Cache is disabled because items are stored on a per-runner basis and thus not shared.  This means
# that it is not possible to share the output of a "bootstrap" job that installs node modules among
# concurrent running jobs in a given stage.
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
# cache:
#   key: "$CI_BUILD_REF_NAME"
#   untracked: true
#   paths:
#     - assets/icons/
#     - node_modules/

before_script:
  # Enable if debugging:
  # - export
  # - which node npm yarn

stages:
  - security
  - lint
  - build
  - test
  - deploy

# TODO: re-enable when appropriate
# NPM audit:
#   stage: security
#   script:
#     - yarn install
#     - yarn audit

flow:
  stage: lint
  script:
    - yarn install
    - yarn run check:flow

lint:
  stage: lint
  artifacts:
    reports:
      junit: test-results/junit/*.xml
  script:
    - yarn install
    - yarn run check:lint

prettier:
  stage: lint
  script:
    - yarn install
    - yarn run check:fmt

build:
  stage: build
  artifacts:
    expire_in: 1 week
    paths:
      - dist
      - es
      - lib
  script:
    - yarn install
    - yarn run build

# Note that *all* jobs involved in testing must produce artifacts containing
# log files generated by software used by the system.
unit:
  stage: test
  artifacts:
    reports:
      junit: junit.xml
  script:
    - yarn install
    - yarn run test
